spring:  
  profiles : dev  
  datasource:  
    name: mydb  
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://127.0.0.1:3306/trade  
    username: root
    password: 123456 
    driver-class-name: com.mysql.jdbc.Driver  
    minIdle: 1  
    maxActive: 2  
    initialSize: 1  
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT '1'  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false
  mvc:
      view:
          prefix:/WEB-INF/views/
server: 
   port:80 
   jsp-servlet:
      class-name:org.apache.jasper.servlet.JspServlet